#!/bin/bash

: ${LOGFILE:=/tmp/ambari_consul_restart.log}
: ${DEBUG:=1}

main(){
  debug "ambari agent restart event triggered."
  ambari-agent restart
  if [ $? -eq 0 ]; then
      debug "Ambari agent restarted."
  else
      error "Ambari agent restart failed."
  fi
}

debug(){
  [[ "$DEBUG" ]] && echo "[DEBUG] $(date) [ambari-agent] $*" >> $LOGFILE
}

error(){
  [[ "$DEBUG" ]] && echo "[ERROR] $(date) [ambari-agent] $*" >> $LOGFILE
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@"
