#!/bin/bash

: ${LOGFILE:=/tmp/ambari_db_consul_reset.log}
: ${DEBUG:=1}

main(){
  debug "$(date) ambari db reset event triggered."
  PGPASSWORD=bigdata psql -h localhost -U ambari  -c "UPDATE pg_database set datallowconn = 'false' where datname = 'postgres'"
  PGPASSWORD=bigdata psql -h localhost -U ambari -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'postgres'"
  PGPASSWORD=bigdata psql -h localhost -U ambari -c "DROP database postgres"
  PGPASSWORD=bigdata psql -h localhost -U ambari -c "CREATE database postgres"
}

debug(){
  [[ "$DEBUG" ]] && echo "[DEBUG] $(date) [ambari-db] $*" >> $LOGFILE
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@"
